### ISSUE TITLE
Refactor CSI Proxy to become a go library in favor of the client/server model

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes-csi/csi-proxy#217]
/assign @mauriciopoppe

**Comment by mauriciopoppe** [comment]
@msau42 yeah we can do that, I wanted to try to release in the v1.x branch so that if we need to have a new release we would have everything set up (if that's needed although that might not happen). I'll proceed with the release in the master branch.

**Comment by mauriciopoppe** [comment]
Updates about the ongoing work:

- The migration effort is complete and it happened in the [`library-development`](https://github.com/kubernetes-csi/csi-proxy/tree/library-development) branch, unit tests and integration tests are running directly in the host.
- We created an alpha tag https://github.com/kubernetes-csi/csi-proxy/releases/tag/v2.0.0-alpha.0 that can already be used for testing, **it's alpha and must not be used in production yet**
- Ongoing effort in the PD CSI Driver to use the alpha tag https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1071, we haven't run presubmit tests with it properly yet (waiting on test-infra fixes)

**Comment by alexander-ding** [comment]
Following up on @mauriciopoppe 's points:

- We are drafting's a [release blog post](https://docs.google.com/document/d/18WwuKSONG_qkD3vaoppL_ikeDL0Ms0Wwv7HsyN8Oel0/edit?usp=sharing) for CIS Proxy v2. Any feedback would be greatly appreiated.

**Comment by davhdavh** [comment]
For anyone interested, there is no reason to wait for v2 to use host process...

This is all the yaml you need to get it working.

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: csi-proxy
  name: csi-proxy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: csi-proxy
  template:
    metadata:
      labels:
        k8s-app: csi-proxy
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\SYSTEM"
      hostNetwork: true
      containers:
        - name: csi-proxy
          image: ghcr.io/kubernetes-sigs/sig-windows/csi-proxy:v1.1.2
```
